# Generated by Django 5.0.6 on 2026-06-05 07:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0002_segments_storecustomer'),
        ('stores', '0003_store_showcase_config'),
    ]

    operations = [
        migrations.CreateModel(
            name='ScheduledBroadcast',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField()),
                ('image_url', models.URLField(blank=True, max_length=500)),
                ('repeat', models.CharField(choices=[('once', 'once'), ('daily', 'daily'), ('weekly', 'weekly')], default='once', max_length=8)),
                ('scheduled_at', models.DateTimeField()),
                ('status', models.CharField(choices=[('pending', 'pending'), ('sent', 'sent'), ('failed', 'failed'), ('cancelled', 'cancelled')], default='pending', max_length=10)),
                ('sent_count', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('sent_at', models.DateTimeField(blank=True, null=True)),
                ('store', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='scheduled_broadcasts', to='stores.store')),
            ],
            options={
                'ordering': ['scheduled_at'],
            },
        ),
    ]
