import pytest
from apps.stores.models import Store

pytestmark = pytest.mark.django_db


def test_store_slug_autogenerated():
    s = Store.objects.create(name="My Shop", phone="998900000000")
    assert s.slug == "my-shop"
    assert s.is_active is True
    assert s.currency_code == "uz"


def test_store_slug_unique_suffix():
    Store.objects.create(name="Shop", phone="1")
    s2 = Store.objects.create(name="Shop", phone="2")
    assert s2.slug == "shop-2"
