# Generated by Django 5.0.6 on 2026-06-02 05:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0001_initial'),
        ('stores', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_ru', models.CharField(max_length=255)),
                ('name_uz', models.CharField(max_length=255)),
                ('description_ru', models.TextField(blank=True)),
                ('description_uz', models.TextField(blank=True)),
                ('price', models.DecimalField(decimal_places=2, max_digits=12)),
                ('unit', models.CharField(choices=[('dona', 'dona'), ('kg', 'kg'), ('litr', 'litr'), ('portsiya', 'portsiya')], default='dona', max_length=16)),
                ('photo_url', models.URLField(blank=True)),
                ('in_stock', models.BooleanField(default=True)),
                ('is_hidden', models.BooleanField(default=False)),
                ('sort_order', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='products', to='catalog.category')),
                ('store', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='products', to='stores.store')),
            ],
            options={
                'ordering': ['sort_order', 'id'],
            },
        ),
    ]
