# Generated by Django 5.0.6 on 2026-06-03 03:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0003_rich_product_fields'),
    ]

    operations = [
        migrations.CreateModel(
            name='GlobalProduct',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_uz', models.CharField(max_length=255)),
                ('name_ru', models.CharField(max_length=255)),
                ('barcode', models.CharField(blank=True, db_index=True, max_length=64)),
                ('ikpu', models.CharField(blank=True, max_length=64)),
                ('price', models.DecimalField(decimal_places=2, max_digits=12)),
                ('discount_price', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('unit', models.CharField(default='dona', max_length=16)),
                ('brand', models.CharField(blank=True, max_length=128)),
                ('model', models.CharField(blank=True, max_length=128)),
                ('manufacturer', models.CharField(blank=True, max_length=128)),
                ('weight_kg', models.DecimalField(decimal_places=3, default=0, max_digits=8)),
                ('length_cm', models.DecimalField(decimal_places=2, default=0, max_digits=8)),
                ('width_cm', models.DecimalField(decimal_places=2, default=0, max_digits=8)),
                ('height_cm', models.DecimalField(decimal_places=2, default=0, max_digits=8)),
                ('image_url', models.URLField(blank=True, max_length=500)),
                ('category_path', models.JSONField(blank=True, default=list)),
                ('recommended_category', models.CharField(blank=True, max_length=255)),
            ],
            options={
                'ordering': ['id'],
            },
        ),
    ]
