# Generated by Django 5.0.6 on 2026-06-02 09:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stores', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='store',
            name='card_enabled',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='store',
            name='card_holder',
            field=models.CharField(blank=True, max_length=128),
        ),
        migrations.AddField(
            model_name='store',
            name='card_number',
            field=models.CharField(blank=True, max_length=32),
        ),
        migrations.AddField(
            model_name='store',
            name='card_payment_title',
            field=models.CharField(blank=True, max_length=128),
        ),
        migrations.AddField(
            model_name='store',
            name='cash_enabled',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='store',
            name='click_url',
            field=models.CharField(blank=True, max_length=256),
        ),
        migrations.AddField(
            model_name='store',
            name='close_time',
            field=models.CharField(blank=True, max_length=5),
        ),
        migrations.AddField(
            model_name='store',
            name='delivery_base_price',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
        migrations.AddField(
            model_name='store',
            name='delivery_base_radius',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=6),
        ),
        migrations.AddField(
            model_name='store',
            name='delivery_fixed_price',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
        migrations.AddField(
            model_name='store',
            name='delivery_price_per_km',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
        migrations.AddField(
            model_name='store',
            name='delivery_pricing_mode',
            field=models.CharField(default='dynamic', max_length=8),
        ),
        migrations.AddField(
            model_name='store',
            name='menu_view_mode',
            field=models.CharField(default='grid_categories', max_length=24),
        ),
        migrations.AddField(
            model_name='store',
            name='minimum_order_amount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
        migrations.AddField(
            model_name='store',
            name='msg_cancelled',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='store',
            name='msg_delivered',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='store',
            name='msg_delivering',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='store',
            name='msg_new',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='store',
            name='msg_preparing',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='store',
            name='open_time',
            field=models.CharField(blank=True, max_length=5),
        ),
        migrations.AddField(
            model_name='store',
            name='payme_enabled',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='store',
            name='payme_merchant_id',
            field=models.CharField(blank=True, max_length=64),
        ),
        migrations.AddField(
            model_name='store',
            name='payme_url',
            field=models.CharField(blank=True, max_length=256),
        ),
        migrations.AddField(
            model_name='store',
            name='service_fee',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
        migrations.AddField(
            model_name='store',
            name='support_username',
            field=models.CharField(blank=True, max_length=64),
        ),
        migrations.AddField(
            model_name='store',
            name='timezone',
            field=models.CharField(default='Asia/Tashkent', max_length=64),
        ),
        migrations.AddField(
            model_name='store',
            name='ui_font_family',
            field=models.CharField(default='sans', max_length=16),
        ),
        migrations.AddField(
            model_name='store',
            name='ui_primary_color',
            field=models.CharField(blank=True, max_length=16),
        ),
        migrations.AddField(
            model_name='store',
            name='ui_theme',
            field=models.CharField(default='classic', max_length=16),
        ),
        migrations.AddField(
            model_name='store',
            name='uzum_url',
            field=models.CharField(blank=True, max_length=256),
        ),
    ]
