# Generated by Django 5.0.6 on 2026-06-02 18:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stores', '0002_store_card_enabled_store_card_holder_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='store',
            name='showcase_config',
            field=models.JSONField(blank=True, default=dict),
        ),
    ]
